# fly.toml app configuration file generated for smartrade on 2023-09-22T09:10:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartrade"
primary_region = "hkg"
kill_signal = "SIGTERM"
swap_size_mb = 1024 

[build]

[env]
  PHX_HOST = "smartrade.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true 
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
