[package]
name = "rust_totp"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rust_totp"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
totp-rs = "5.4.0"
